### PR TITLE
feat: add base lambda iamge

### PR DESCRIPTION
**Pull request by j0nnylester**
Some of our lambda repos use the aws node image but are showing errors due to inconsistencies between npm and yarn in our pipelines.

### CODE REVIEW

**Review by Tom-Hudson — APPROVED** [review]
Looks good to me!

**Comment by daveshepherd** [comment]
You'll need to update the `.circleci` config to build this in line with the other base images.

**Comment by scotttimmins** [comment]
Unfortunately the versions of the amazon image are not compatible with the contents of the .version file (see [here](https://hub.docker.com/r/amazon/aws-lambda-nodejs/tags))

**Comment by j0nnylester** [comment]
Node v6 and v8 do no exist for the amazon/aws-lambda-nodejs image so they have been removed. It'd be nice to add node v16, but again, it doesn't;t exist for the amazon/aws-lambda-nodejs image.

**Review by daveshepherd — APPROVED** [review]

**Review by yoz2326 — APPROVED** [review]

**Comment by j0nnylester** [comment]
Added node v16 in this PR: https://github.com/WealthWizardsEngineering/ww-base-node/pull/4. This will cause issues for this branch because there isn't a node v16 image for [amazon/aws-lambda-nodejs](https://hub.docker.com/r/amazon/aws-lambda-nodejs/tags).

**Pull request closed without merging**
